# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 06bc848d0b1f6b343363ced098d2aeb23bece0989c3e60a21dbbdfa3b2dc89212ace9dc2b8b0cd1b535468f344020d5ad0e2d3f91cb9e57eec09b7615943a7ed

test:
  secret_key_base: 4b58de93aaa2239018f40d8831a0ed5b2857eb04b1de03e8efb92f836e9b8c5aa9f93ed7a5c115241ae66513f19eabdd35dcdac6b4899de5c32ae6efeb24d9ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
